import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.scss';
import Layout from '../components/Fayout';
import { StoreProvider } from '@/store';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


const RootLayout = function ({ children }: { children: React.ReactNode }) {
  const initialValue = {
    user: {
      userInfo: {
        userId: cookies().get('userId')?.value,
        nickname: cookies().get('nickname')?.value,
        avatar: cookies().get('avatar')?.value,
      },
    },
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider initialValue={initialValue}>
          <Layout>{children}</Layout>
        </StoreProvider>
      </body>
    </html>
  );
};

export default RootLayout;
