import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.scss';
import Layout from '../components/Fayout';
import { StoreProvider } from '@/store';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider initialValue={{ user: {} }}>
          <Layout>{children}</Layout>
        </StoreProvider>
      </body>
    </html>
  );
}
